### ISSUE TITLE
this package seems to need typing_extension, but typing extension isn't installed by default

### ISSUE THREAD

**Issue by jonmooser** [bwindsor/typed-config#11]
On a python 3.11 installation I ran 
pip3 install typed-config

But when I tried to 
from typedconfig import ...
Python complained that typing_extension was missing. 

This was fixed easily enough with 
pip3 install typing_extension. 

But should the dependencies automatically be included with the initial pip install?

**Comment by bwindsor** [comment]
You're right. This package was meant to have zero dependencies, but for python 3.7 Literal is used which requires typing_extensions. For python >=3.8 it's included in typing but the code still tries to use extensions. I'll try to get that fixed.

**Comment by bwindsor** [comment]
This should be fixed in release `1.2.1`. Thanks for spotting it, let me know if you're still getting issues.

**Comment by jonmooser** [comment]
Yep - that seems to fix it. Thanks!
