### ISSUE TITLE
boolean settings unsupported?

### ISSUE THREAD

**Issue by luziferius** [bwindsor/typed-config#17]
I'm currently porting an app to typed-config. It has a few boolean (and trinary True/False/None) settings, which seem to be not directly supported by typed-config.

See this small, self-contained reproduction script:

``` python
from pathlib import Path
from textwrap import dedent
from typedconfig import *
from typedconfig.source import IniFileConfigSource
Path("./test.ini").write_text(dedent("""\
    [App]
    test = False
    test2 = false
"""))
@section("App")
class App(Config):
    test = key(cast=bool)
    test2 = key(cast=bool)
settings = App()
settings.add_source(IniFileConfigSource("./test.ini"))
settings.read()
# This assert should pass. But both settings.test and settings.test2 are True,
# because the ini-values 'False'/'false' are non-empty, 
# and bool("False") is True
assert settings.test is False and settings.test2 is False
```

This of course is is caused by using `bool` as the cast function. Converting `"True"`/`"False"` to `True`/`False` needs a special comparison function. So I suggest providing something like this in `typedconfig.casts`:
``` python
def bool_cast(value: str) -> bool:
    result = configparser.ConfigParser.BOOLEAN_STATES[value.lower()]
    return result
```
Note on the use of `.lower()`: The default boolean constants stored in `BOOLEAN_STATES` are lower case `"true"`/`"false"`, while Python's string representation of True/False/None is capitalized. To avoid KeyErrors purely because of case differences, I use `lower()` on the input data.

In my project, I have these two functions, which seem to work as intended, and properly parse strings of boolean constants into the correct value:
``` python
def bool_cast(value: str) -> bool:
    result = configparser.ConfigParser.BOOLEAN_STATES[value.lower()] or False  # Coerce None to False
    return result

def opt_bool_cast(value: str) -> OptBool:
    return configparser.ConfigParser.BOOLEAN_STATES[value.lower()]

# For context, somewhere else I extended BOOLEAN_STATES like
configparser.ConfigParser.BOOLEAN_STATES.update({
    "-1": None,
    "unknown": None,
    "none": None,
})
```

**Comment by bwindsor** [comment]
Hi @luziferius, thanks for the suggestion - I've just added this in https://github.com/bwindsor/typed-config/commit/4a8e0f742f20f0edd832f09571def5eca7547f7d and it should be there in release `1.4.0`.

**Comment by luziferius** [comment]
Wow, that was fast! Thank you!

Will bump the version in the requirements as soon as it lands on PyPI. :)

**Comment by bwindsor** [comment]
You caught me exactly as I finished another task so thought I'd just do it quickly straight away!

**Comment by bwindsor** [comment]
Ah looks like Travis doesn't want to deploy automatically any more and wants me to pay. Will try setting up github actions instead.
