### ISSUE TITLE
repr function for Config class

### ISSUE THREAD

**Issue by yzernik** [bwindsor/typed-config#7]
Can we have a repr function for the Config class? This would be useful for debugging.

**Comment by bwindsor** [comment]
@yzernik I've added this in 115e629 - is that what you were hoping for?

As an example for a 2-level hierarchy config:
```
SampleConfig(b='B', child=SampleChildConfig(a='A'))
```

**Comment by yzernik** [comment]
@bwindsor  Yes that's perfect. Could you deploy the latest version to pypi so I can use it?

**Comment by bwindsor** [comment]
Great, it's included in 0.2.2.

**Comment by bwindsor** [comment]
Ah, but 0.2.2 is not on PyPi for some reason, must be something up with Travis, I'll take a look.

**Comment by bwindsor** [comment]
OK - Travis now sorted out, it's there in `0.2.5`
